import Head from 'next/head';
import Link from 'next/link';

export default function Home({ datas }) {
  return (
    <div className='text-md text-slate-500 font-semibold'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Hello Next js</h1>
        <div>
          {datas &&
            datas.map((d, i) => (
              <div key={i}>
                <Link href={`/posts/${d.id}`}>{d.body}</Link>
              </div>
            ))}
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const datas = await fetch(
    'https://jsonplaceholder.typicode.com/posts?_limit=20'
  ).then((res) => res.json());
  return {
    props: {
      datas,
    },
  };
};
