import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import Main from "../components/Main";

export default function Home({ products }) {
  console.log("products", products);
  return (
    <div className="text-md text-slate-500 bg-red-300 font-semibold">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <h1>Hello Next js</h1>
        <Link href={`/author`}>Author</Link> */}
        <Header />
        <Main products={products} />
        {/* <div>
          {products &&
            products.map((d, i) => (
              <div key={i}>
                <Link href={`/posts/${d._id}`}>{d.name}</Link>
              </div>
            ))}
        </div> */}
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const { products, pages, page, count } = await fetch(
    "https://annazone-api.onrender.com/api/products"
  ).then((res) => res.json());
  // console.log("datas", datas.products);

  return {
    props: { products, pages, page, count },
  };
};
// export const getServerSideProps = async () => {
//   const datas = await fetch(
//     "https://jsonplaceholder.typicode.com/posts?_limit=20"
//   ).then((res) => res.json());
//   return {
//     props: {
//       datas,
//     },
//   };
// };
